[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "compara_prg"
version = "0.1.0"
description = "Compara PRG tools"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
include = ["compara_prg*"]
